<?xml version="1.0"?>
<package format="3">
  <name>mujoco</name>
  <version>1.0.0</version>
  <description>MuJoCo simulation backend for UR5e + Robotiq 2F-85</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>mujoco_ros2_control_plugins</depend>
  <depend>mujoco_ros2_control_msgs</depend>
  <depend>mujoco_vendor</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>
  <exec_depend>description</exec_depend>
  <exec_depend>mujoco_ros2_control</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>position_controllers</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
